version: '3'
services:
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -h 0.0.0.0 -m '0'
    stdin_open: true
    tty: true
    ports:
      - '8545:8545'

  redis:
    image: redis
    ports:
      - '6379:6379'
    command:
      redis-server

  processor:
    build: ./
    depends_on:
      - ganachecli
      - redis
    command:
      node index.js -e test
